<?php if ($comment = $block->getOrderComment()):?>
<div class="block block-order-details-view">
    <div class="block-content">
        <div class="box box-order-comment">
            <strong class="box-title"><span><?= __('Order Comment') ?></span></strong>
            <div class="box-content">
               <?= $block->getOrderCommentHtml();?>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>